### PR TITLE
Objects Automated Test - LPS-156703 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LPS-156703

### CODE REVIEW

**Comment by andreefarias** [comment]
Hey @timpak!

Maybe the expression builder with conditions with **custom integers** is a bug. I'll look more with the developers.

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by timpak** [comment]
Gotcha, let me know the ticket number if you do open the bug, @andreefarias

**Comment by andreefarias** [comment]
The bugs it's was opened on the ticket: [LPS-163007](https://issues.liferay.com/browse/LPS-163007), is related automated test.

**Comment by timpak** [comment]
Thanks! Also, do you need me to review this? It looks like it's already in master: https://github.com/liferay/liferay-portal/commit/2cebf0b31f8f1bb665d6604b6bad1ca813059176

**Comment by andreefarias** [comment]
My bad. I forwarded unintentionally the PR, it was to be **ci:test:sf**. However, I believe that this testcase is good, except for steps blocked by the bug.

I can add this step after, when the bug is fixed. What do you think? @timpak

**Comment by timpak** [comment]
@andreefarias yeah that's fine, you can add them after the bug is fixed. 

As long as the test is passing, it's ok. I took a quick look at the logic and it seems fine for now.

**Pull request closed without merging**
