### PR TITLE
Objects Automated Test - LPS-156800, LPS-156801, LPS-156807 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LPS-156800
https://issues.liferay.com/browse/LPS-156801
https://issues.liferay.com/browse/LPS-156807

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Review by timpak — COMMENTED** [review]
Hi @andreefarias, next time please add  and edit in separate commits. Also, you should get in the habit of writing clear commit messages so people can easily tell what the code is doing. 

Something like this:
- LPS-156807 Add paths and macros to XXXX
- LPS-156807 Edit the paths and macros to XXXX

**Comment by timpak** [comment]
LGTM! See https://github.com/timpak/liferay-portal/pull/308

**Pull request closed without merging**
