### PR TITLE
Objects Automated Test - LPS-152065 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LPS-152065

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by timpak** [comment]
The test is fine but I'm running into merge conflicts when trying to cherrypick the commit into my review branch. After I forward https://github.com/timpak/liferay-portal/pull/225, I'll try again.

**Comment by timpak** [comment]
Gotcha. I'll edit the test case name then to make it clearer. Thanks!

**Comment by timpak** [comment]
Ah, I can't cleanly cherrypick this. I'll send in your tests after the current test branch I have is merged.

**Comment by timpak** [comment]
See https://github.com/timpak/liferay-portal/pull/233

**Pull request closed without merging**
