### PR TITLE
Objects Automated Test - LPS-161885 | master 

### PR DESCRIPTION
**Pull request by alessandromalves**
https://issues.liferay.com/browse/LPS-161885

In addition to this test I updated a path(ObjectAdmin#LABEL_DROPDOWN)

### CODE REVIEW

**Comment by alessandromalves** [comment]
ci:test:sf

**Comment by alessandromalves** [comment]
ci:stop

**Comment by alessandromalves** [comment]
ci:stop

**Review by timpak — APPROVED** [review]
Great job, @alessandromalves LGTM!

**Comment by timpak** [comment]
Added to https://github.com/liferay-bpm-qa/liferay-portal/pull/9

**Comment by alessandromalves** [comment]
ci:a

**Pull request closed without merging**
