### PR TITLE
Objects Automated Test - LPS-162185, LPS-162190, LPS-162191, LPS-162192 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LPS-162185
https://issues.liferay.com/browse/LPS-161890 (incomplete)
https://issues.liferay.com/browse/LPS-161891
https://issues.liferay.com/browse/LPS-161892

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
Hey @timpak,

The commit **CanCreateEntryWithAggregationField** is incomplete because there is a bug on custom object entries when there is a custom aggregation field.

I moved the ticket to open and linked to the bug. I sent the first part because I used the macro / paths in another testcases.

**Review by timpak — APPROVED** [review]
Good job with these tests @andreefarias! In the future, you can always add a workaround for the test to avoid the bug. If there's no workaround, you can include all of the steps and ignore the test until the bug is fixed. You would need to create a ticket to add the workaround/ignore and another ticket to remove it once the bug is fixed. Does that make sense?

Also, how familar are you with Aggregation Fields? I'm looking into expanding our test coverage here since we're not actually using the fields with the object entries and I could use some help creating test scenarios.

**Comment by timpak** [comment]
Added to https://github.com/timpak/liferay-portal/pull/330

**Comment by andreefarias** [comment]
> Good job with these tests @andreefarias! In the future, you can always add a workaround for the test to avoid the bug. If there's no workaround, you can include all of the steps and ignore the test until the bug is fixed. You would need to create a ticket to add the workaround/ignore and another ticket to remove it once the bug is fixed. Does that make sense?
> 
> Also, how familar are you with Aggregation Fields? I'm looking into expanding our test coverage here since we're not actually using the fields with the object entries and I could use some help creating test scenarios.

Thank you!

It makes sense. I will create the tickets and link them. About Aggregation Fields, I made some manual validations and I know a little.

cc: @timpak

**Pull request closed without merging**
