### PR TITLE
LPS-160651 | master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LPS-160651
Submit to master.

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Review by timpak — APPROVED** [review]
LGTM!

**Comment by timpak** [comment]
ci:forward

**Comment by timpak** [comment]
@chaowang-123 in the future, you can send your tests to https://github.com/liferay-bpm-qa for review. We recently created guidelines for test review [here](https://liferay.atlassian.net/wiki/spaces/DXPL/pages/2114356408/Test+Review+Guidelines).

**Pull request closed without merging**
